#!/bin/bash

N=70
Routers=($(docker ps -f "name=(-router)|(-r[0-9])" -q))
#PROXY=($(docker ps -f "name=proxy" -q))


for router in $(shuf --input-range=0-$(( ${#Routers[*]} - 1 )) -n ${N})
  do  
    docker exec ${Routers[$router]} sh -c "birdc restart all" 
    sleep 6
  done

